"""Deterministic long-help resources for generated Starlink wrappers."""

from __future__ import annotations

from collections import defaultdict
import hashlib
from html import unescape
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

from html_to_rst import html_to_rst


SOURCE_OVERRIDES = {
    ("ccdpack", "ccdhelp"): "ccdhelp.f",
    ("figaro", "grow"): "figaro4/grow.f",
}

PACKAGE_HELP_FALLBACKS = {("figaro", "table")}

_SOURCE_SUFFIXES = {".c", ".f", ".py"}
_H1 = re.compile(r"<h1\b[^>]*>(.*?)</h1>", re.IGNORECASE | re.DOTALL)
_TAG = re.compile(r"<[^>]+>")
_HLP_HEADING = re.compile(r"^([1-4])\s+(.+?)\s*$")


def _source_index(source_root: Path) -> dict[str, list[Path]]:
    index: dict[str, list[Path]] = defaultdict(list)
    for path in sorted(source_root.rglob("*")):
        if path.is_file() and path.suffix.lower() in _SOURCE_SUFFIXES:
            index[path.stem.lower()].append(path)
    return index


def _select_source(
    source_root: Path,
    package: str,
    command: str,
    index: dict[str, list[Path]],
) -> Path | None:
    key = (package, command)
    if key in PACKAGE_HELP_FALLBACKS:
        return None

    override = SOURCE_OVERRIDES.get(key)
    if override is not None:
        source = source_root / override
        if not source.is_file():
            raise FileNotFoundError(source)
        return source

    candidates: list[Path] = []
    for stem in (command, f"{package}_{command}"):
        candidates.extend(index.get(stem, ()))
    candidates = sorted(set(candidates))
    if not candidates:
        return None
    if len(candidates) != 1:
        relative = ", ".join(str(path.relative_to(source_root)) for path in candidates)
        raise RuntimeError(
            f"Ambiguous help source for {package}.{command}: {relative}; "
            "add an explicit SOURCE_OVERRIDES entry or "
            "PACKAGE_HELP_FALLBACKS entry"
        )
    return candidates[0]


def _heading_text(value: str) -> str:
    return " ".join(unescape(_TAG.sub("", value)).split()).casefold()


def _extract_command_html(html: str, command: str) -> str:
    headings = list(_H1.finditer(html))
    matches = [
        index
        for index, heading in enumerate(headings)
        if _heading_text(heading.group(1)) == command.casefold()
    ]
    if len(matches) != 1:
        found = [_heading_text(heading.group(1)) for heading in headings]
        raise RuntimeError(
            f"Expected one H1 for {command!r}, found {matches!r}; headings={found!r}"
        )
    index = matches[0]
    start = headings[index].start()
    end = headings[index + 1].start() if index + 1 < len(headings) else len(html)
    return html[start:end]


def _run_prohtml(
    installation: Path,
    source: Path,
    destination: Path,
    adam_user: Path,
) -> None:
    prohtml = installation / "bin" / "sst" / "prohtml"
    if not prohtml.is_file():
        raise FileNotFoundError(prohtml)

    environment = os.environ.copy()
    environment["STARLINK_DIR"] = str(installation)
    environment["ADAM_USER"] = str(adam_user)
    environment["STAR_TEMP"] = str(adam_user.parent / "tmp")
    environment["PATH"] = os.pathsep.join(
        (str(installation / "bin"), environment.get("PATH", ""))
    )
    environment["LD_LIBRARY_PATH"] = os.pathsep.join(
        value
        for value in (
            str(installation / "lib"),
            environment.get("LD_LIBRARY_PATH", ""),
        )
        if value
    )

    adam_user.mkdir(parents=True, exist_ok=True)
    Path(environment["STAR_TEMP"]).mkdir(parents=True, exist_ok=True)
    completed = subprocess.run(
        [
            str(prohtml),
            f"in={source}",
            "reformat=true",
            "inclusion=false",
            f"out={destination}",
            "accept",
        ],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        env=environment,
    )
    if completed.returncode:
        raise RuntimeError(
            f"prohtml failed for {source} with status {completed.returncode}\n"
            f"stdout:\n{completed.stdout}\n"
            f"stderr:\n{completed.stderr}"
        )


def _strip_trailing_whitespace(text: str) -> str:
    return "\n".join(line.rstrip() for line in text.splitlines()).rstrip() + "\n"


def _resource_text(
    html: str,
    source: Path,
    source_repo: Path,
    release: str,
    commit: str,
) -> str:
    relative = source.relative_to(source_repo).as_posix()
    provenance = (
        ".. Generated by starlink-pywrapper/helperscripts/generate_2025a.py.\n"
        f".. Starlink release: {release}\n"
        f".. Starlink source commit: {commit}\n"
        f".. Starlink source file: {relative}\n\n"
    )
    return provenance + _strip_trailing_whitespace(html_to_rst(html))


def _help_sections(help_file: Path) -> dict[str, list[str]]:
    """Return command sections from a Starlink package ``.hlp`` file."""

    sections: dict[str, list[str]] = {}
    command: str | None = None
    for line in help_file.read_text(encoding="latin-1").splitlines():
        heading = _HLP_HEADING.match(line)
        if heading and heading.group(1) == "1":
            command = heading.group(2).strip().casefold()
            sections[command] = [line]
        elif command is not None:
            sections[command].append(line)
    return sections


def _hlp_to_rst(lines: list[str]) -> str:
    """Convert one Starlink package-help section to conservative RST."""

    adornments = {"1": "#", "2": "-", "3": "^", "4": '"'}
    output: list[str] = []
    paragraph: list[str] = []

    def flush() -> None:
        if paragraph:
            output.append("\n".join(paragraph).rstrip())
            output.append("")
            paragraph.clear()

    for raw_line in lines:
        heading = _HLP_HEADING.match(raw_line)
        if heading:
            flush()
            title = heading.group(2).strip()
            output.extend((title, adornments[heading.group(1)] * len(title), ""))
        elif raw_line.strip():
            line = raw_line.rstrip()
            paragraph.append(line[1:] if line.startswith(" ") else line)
        else:
            flush()
    flush()
    return "\n".join(output).rstrip() + "\n"


def _hlp_resource_text(
    lines: list[str],
    help_file: Path,
    source_repo: Path,
    release: str,
    commit: str,
) -> str:
    relative = help_file.relative_to(source_repo).as_posix()
    provenance = (
        ".. Generated by starlink-pywrapper/helperscripts/generate_2025a.py.\n"
        f".. Starlink release: {release}\n"
        f".. Starlink source commit: {commit}\n"
        f".. Starlink source file: {relative}\n"
        ".. Source format: Starlink package help fallback\n\n"
    )
    return provenance + _strip_trailing_whitespace(_hlp_to_rst(lines))


def generate_package_help(
    *,
    source_repo: Path,
    source_root: Path,
    installation: Path,
    output: Path,
    baseline: Path,
    package: str,
    package_help: Path | None = None,
    command_paths: dict[str, str],
    release: str,
    commit: str,
) -> list[dict[str, str]]:
    """Generate all source-backed help resources for one wrapper package."""

    help_dir = output / f"{package}_help"
    baseline_dir = baseline / f"{package}_help"
    baseline_commands = (
        {path.stem for path in baseline_dir.glob("*.rst")}
        if baseline_dir.is_dir()
        else set()
    )
    index = _source_index(source_root)
    if package_help is not None:
        if not package_help.is_file():
            raise FileNotFoundError(package_help)
        help_files = [package_help]
    else:
        root_help_file = source_root / f"{package}.hlp"
        help_files = (
            [root_help_file]
            if root_help_file.is_file()
            else sorted(source_root.rglob(f"{package}.hlp"))
        )
    if len(help_files) > 1:
        relative = [str(path.relative_to(source_root)) for path in help_files]
        raise RuntimeError(
            f"Expected at most one package-level help file, found {relative!r}"
        )
    help_file = help_files[0] if help_files else None
    help_sections = _help_sections(help_file) if help_file is not None else {}
    resources: dict[str, tuple[str, str]] = {}

    with tempfile.TemporaryDirectory(prefix=f"starlink-{package}-help-") as temporary:
        temporary_path = Path(temporary)
        adam_user = temporary_path / "adam"
        for command, executable in sorted(command_paths.items()):
            if executable.startswith("__REMOVED__:"):
                continue
            source = _select_source(source_root, package, command, index)
            text: str | None = None
            source_path: Path | None = None
            if source is not None:
                html_path = temporary_path / f"{command}.html"
                try:
                    _run_prohtml(installation, source, html_path, adam_user)
                    html = _extract_command_html(
                        html_path.read_text(encoding="utf-8", errors="strict"),
                        command,
                    )
                except RuntimeError:
                    pass
                else:
                    text = _resource_text(html, source, source_repo, release, commit)
                    source_path = source

            if text is None:
                section = help_sections.get(command.casefold())
                if section is None or help_file is None:
                    continue
                text = _hlp_resource_text(
                    section, help_file, source_repo, release, commit
                )
                source_path = help_file

            assert source_path is not None
            resources[command] = (
                text,
                source_path.relative_to(source_repo).as_posix(),
            )

    missing_baseline = sorted((baseline_commands & set(command_paths)) - set(resources))
    if missing_baseline:
        raise RuntimeError(
            f"Could not regenerate existing {package} help resources: "
            + ", ".join(missing_baseline)
        )

    staging = output / f".{package}_help.generated"
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)
    records = []
    for command, (text, source_path) in sorted(resources.items()):
        path = staging / f"{command}.rst"
        path.write_text(text, encoding="utf-8", newline="\n")
        records.append(
            {
                "command": command,
                "package": package,
                "path": f"starlink/{package}_help/{command}.rst",
                "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
                "source": source_path,
            }
        )

    if help_dir.exists():
        shutil.rmtree(help_dir)
    staging.replace(help_dir)
    return records


def write_help_manifest(
    path: Path,
    records: list[dict[str, str]],
    *,
    release: str,
    commit: str,
) -> None:
    """Write the deterministic checked-in help provenance manifest."""

    document = {
        "schema_version": 1,
        "starlink_release": release,
        "starlink_source_commit": commit,
        "resource_count": len(records),
        "resources": sorted(records, key=lambda item: item["path"]),
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(document, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
